# Generated by Django 5.1.3 on 2024-11-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.TextField(max_length=20)),
                ('itemquantity', models.TextField(max_length=10)),
                ('itemprice', models.IntegerField(null=True)),
                ('itemqnt', models.IntegerField(null=True)),
                ('userid', models.TextField(max_length=20)),
                ('total', models.IntegerField(null=True)),
                ('imag', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.IntegerField(null=True)),
                ('userids', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('quantity', models.TextField(max_length=10)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coffee_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Orderp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('userid', models.TextField(max_length=20)),
                ('amount', models.IntegerField(null=True)),
                ('ispaid', models.BooleanField(default=False)),
                ('razorpay_order_id', models.CharField(max_length=20, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=20, null=True)),
                ('razorpay_payment_signature', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
