# Generated by Django 5.1.3 on 2025-01-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iuserids', models.TextField(max_length=20)),
                ('iamount', models.IntegerField(null=True)),
                ('irazorpay_order_id', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
