# Generated by Django 5.1.3 on 2025-01-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansh', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='subtotal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='tax',
            field=models.IntegerField(null=True),
        ),
    ]
